/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author os
 */
public class suportCalculateTax extends javax.swing.JFrame {

    /**
     * Creates new form CalculateTax
     */
    private int id;
    private String name;
    private int tax_code;
    private String address;
    private Float total;
    private String tax_period;

    public suportCalculateTax() {
        initComponents();
    }

    public suportCalculateTax(int id, String name, int tax_code, String address, Float total, String tax_period) {
        this.id = id;
        this.name = name;
        this.tax_code = tax_code;
        this.address = address;
        this.total = total;
        this.tax_period = tax_period;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HỖ TRỢ TÍNH THUẾ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 320, 50));

        jLabel2.setText("Tổng thu nhập chịu thuế");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 85, 156, 26));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 305, 26));

        jLabel3.setText("Các khoản được miễn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 129, 148, 32));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 305, 32));

        jLabel4.setText("Thu nhập chịu thuế");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 188, 136, 24));

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 313, 35));

        jLabel5.setText("Các khoản được giảm trừ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 31));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 310, 30));

        jLabel6.setText("Thu nhập tính thuế");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jButton1.setText("Tính chịu thuế");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 140, -1));

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 310, 30));

        jLabel7.setText("Thuế TNCN phải nộp ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 310, 30));

        jButton2.setText("Tính thuế");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 440, 139, -1));

        jButton3.setText("Tính thuế phải nộp");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 537, 139, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 248, 200, 30));

        jLabel8.setText("Giảm trừ gia cảnh cá nhân");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 247, -1, -1));

        jLabel9.setText("Giảm trừ gia cảnh cho người phụ thuộc");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 298, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 200, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("không có");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("1 người");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("2 người");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 200, 30));

        jLabel10.setText("BHXH,..");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 336, -1, -1));

        btnBack.setText("Xác nhận");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public float getTotal() {
        return total;
    }

    public void setTotal(float total) {
        this.total = total;
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            float input1 = Float.parseFloat(jTextField1.getText());
            float input2 = Float.parseFloat(jTextField2.getText());
            if (input1 < 0 || input2 < 0) {
                JOptionPane.showMessageDialog(this, "Quý khách chưa nhập đủ. Những ô không có vui lòng nhập 0 !");
            }
            float out = input1 - input2;
            String output3 = out + "";
            System.out.println(output3);
            jTextField3.setText(output3);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Quý khách chưa nhập đủ. Những ô không có vui lòng nhập 0 !");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //cai kiem tra input la so hay khong thi m viet nhe, phai la so thi moi dung duoc o duoi
        try {
            float input1 = Float.parseFloat(jTextField3.getText());
            float phuthuoc = 0;
            if (jRadioButton1.isSelected()) {
                phuthuoc = 0;
                String p = phuthuoc + "";
                jTextField8.setText(p);
            } else if (jRadioButton2.isSelected()) {
                phuthuoc = 3600000;
                String p = phuthuoc + "";
                jTextField8.setText(p);
            } else if (jRadioButton3.isSelected()) {
                phuthuoc = 3600000 * 2;
                String p = phuthuoc + "";
                jTextField8.setText(p);
            }
            float bh = (float) (input1 * (0.08 + 0.015 + 0.01));
            String bhxh = bh + "";
            jTextField9.setText(bhxh);
            float canhan = Float.parseFloat(jTextField7.getText());
            float giamtru = phuthuoc + bh + canhan;
            String giam = giamtru + "";
            jTextField4.setText(giam);
            float out = input1 - giamtru;
            String output3 = out + "";
            jTextField5.setText(output3);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Quý khách chưa nhập đủ. Những ô không có vui lòng nhập 0 !");
        }

//        float out = input1-input2;
//        String output3 = out+"";
//        jTextField5.setText(output3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            float input1 = Float.parseFloat(jTextField5.getText());
            float ttncn = 0;
            if (input1 < 5000000) {
                ttncn = 0;
            } else if (input1 == 5000000) {
                ttncn = 250000;
            } else if (input1 <= 10000000) {
                ttncn = (float) (250000 + (input1 - 5000000) * 0.1);
            } else if (input1 <= 18000000) {
                ttncn = (float) (250000 + 5000000 * 0.1 + (input1 - 10000000) * 0.15);
            } else if (input1 <= 32000000) {
                ttncn = (float) (250000 + 5000000 * 0.1 + 8000000 * 0.15 + (input1 - 18000000) * 0.2);
            } else if (input1 <= 52000000) {
                ttncn = (float) (250000 + 5000000 * 0.1 + 8000000 * 0.15 + 14000000 * 0.2 + (input1 - 32000000) * 0.25);
            } else if (input1 <= 80000000) {
                ttncn = (float) (250000 + 5000000 * 0.1 + 8000000 * 0.15 + 14000000 * 0.2 + 20000000 * 0.25
                        + (input1 - 52000000) * 0.3);
            } else if (input1 > 80000000) {
                ttncn = (float) (250000 + 5000000 * 0.1 + 8000000 * 0.15 + 14000000 * 0.2 + 20000000 * 0.25
                        + 28000000 * 0.3 + (input1 - 80000000) * 0.35);
            }
            String output3 = ttncn + "";
            jTextField6.setText(output3);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Quý khách chưa nhập đủ. Những ô không có vui lòng nhập 0");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        Float total = Float.parseFloat(jTextField6.getText());

        supportTax_dialog t = new supportTax_dialog(id, name, tax_code, address, tax_period);
        t.getjTextField2().enableInputMethods(false);
        t.getjTextField2().setText(total + "");
        t.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suportCalculateTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suportCalculateTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suportCalculateTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suportCalculateTax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suportCalculateTax().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
