/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TaxDeclareDao;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicSplitPaneUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import model.*;

/**
 *
 * @author BVCN 88
 */
public class TaxDeclareView extends javax.swing.JFrame {

    int userAccountId;
    String name;
    int taxcode;
    TaxDeclareDao deDao;
    ArrayList<JTextField> listText;

    public TaxDeclareView() {
        initComponents();
        List<JTextField> list = Arrays.asList(txt4, txt5, txt6, txt7, txt8, txt9, txt10, txt11, txt22, txt23, txt24, txt25, txt26, txt27, txt28, txt29, txt30, txt31, txt32,
                 txt33, txt34, txt35, txt36, txt37);
        listText = new ArrayList<>();
        listText.addAll(list);
    }
     
    public TaxDeclareView(int userID, String taxPeriod, String start, String time, String name, int taxcode) {
        initComponents();
        deDao = new TaxDeclareDao();
        this.userAccountId = userID;
        this.name = name;
        this.taxcode = taxcode;
        txt1.setText(taxPeriod);
        txt2.setText(start);
        txt3.setText(time);
        txt4.setText(name);
        txt5.setText(String.valueOf(taxcode));
        System.out.println(userAccountId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt22 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt28 = new javax.swing.JTextField();
        txt29 = new javax.swing.JTextField();
        txt30 = new javax.swing.JTextField();
        txt31 = new javax.swing.JTextField();
        txt32 = new javax.swing.JTextField();
        txt33 = new javax.swing.JTextField();
        txt34 = new javax.swing.JTextField();
        txt35 = new javax.swing.JTextField();
        txt36 = new javax.swing.JTextField();
        txt37 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1247, 2010));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 2000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TỜ KHAI THUẾ THU NHẬP CÁ NHÂN - MẪU 02 KK/TNCN ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("(Áp dụng cho cá nhân cư trú và không cư trú có thu nhập từ  tiền lương , tiền công khai thuế trực tiếp với cơ quan thuế )");

        jLabel3.setText("[1] Kỳ tính thuế: ");

        txt1.setEnabled(false);

        jLabel4.setText("[2] Lần đầu :");

        txt2.setEnabled(false);

        jLabel5.setText("[3] Bổ sung lần thứ :");

        txt3.setEnabled(false);

        jLabel6.setText("[4]   Tên người nộp thuế");

        jLabel7.setText("[5]    Mã số thuế:");

        jLabel8.setText("[12]   Tên đại lý thuế (nếu có):  ");

        jLabel9.setText("[13]   Mã số thuế đại lý:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("STT");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Mã chỉ tiêu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Chỉ tiêu");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Số tiền");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("I                 Cá nhân cư trú có thu nhập từ tiền lương, tiền công:");

        jLabel15.setText("1                 Cá nhân có thu nhập ổn định theo quý không phải nộp tờ khai các quý tiếp theo                                                [21]     ");

        jLabel16.setText("2                Tổng thu nhập chịu thuế phát sinh trong kỳ                                                                                                                   [22]");

        jLabel17.setText("3                Trong đó thu nhập chịu thuế được miễn giảm theo Hiệp định                                                                                  [23]");

        jLabel18.setText("4                Tổng các khoản giảm trừ                                                                                                                                                   [24]");

        jLabel19.setText("     a.           Cho bản thân                                                                                                                                                                      [25]");

        jLabel20.setText("     b.          Cho người phụ thuộc                                                                                                                                                         [26]");

        jLabel21.setText("     c.          Cho từ thiện, nhân đạo, khuyến học                                                                                                                                [27]");

        jLabel22.setText("     d.          Các khoản đóng bảo hiểm được trừ                                                                                                                               [28]");

        jLabel23.setText("     e.           Khoản đóng quỹ hưu trí tự nguyện được trừ                                                                                                                 [29]");

        jLabel24.setText("5                Tổng thu nhập tính thuế                                                                                                                                                     [30]");

        jLabel25.setText("6                Tổng số thuế thu nhập cá nhân phát sinh trong kỳ                                                                                                       [31]");

        jLabel26.setText("7                Tổng thu nhập chịu thuế làm căn cứ tính giảm thuế                                                                                                     [32]");

        jLabel27.setText("8                Tổng số thuế thu nhập cá nhân được giảm                                                                                                                   [33]");

        jLabel28.setText("9                Tổng số thuế thu nhập cá nhân phải nộp                                                                                                                       [34]");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("II               Cá nhân không cư trú có thu nhập từ tiền lương, tiền công:");

        jLabel30.setText("1                Tổng thu nhập tính thuế                                                                                                                                                      [35]");

        jLabel31.setText("2               Mức thuế suất                                                                                                                                                                        [36]");

        jLabel32.setText("3               Tổng số thuế thu nhập cá nhân phải nộp                                                                                                                        [37]");

        jLabel33.setText("NHÂN VIÊN ĐẠI LÝ THUẾ");

        jLabel34.setText("Họ và  tên");

        jLabel35.setText("Chứng chỉ hành nghề số");

        jLabel36.setText("Người kí");

        jLabel37.setText("Ngày kí");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton2.setText("Nhập lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txt22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt22FocusLost(evt);
            }
        });

        txt23.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt23FocusLost(evt);
            }
        });

        txt24.setEnabled(false);
        txt24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt24FocusGained(evt);
            }
        });

        txt25.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt25FocusLost(evt);
            }
        });

        txt26.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt26FocusLost(evt);
            }
        });

        txt27.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt27FocusLost(evt);
            }
        });

        txt28.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt28FocusLost(evt);
            }
        });

        txt29.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt29FocusLost(evt);
            }
        });

        txt30.setEnabled(false);

        txt31.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt31FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt31FocusLost(evt);
            }
        });

        txt32.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt32FocusLost(evt);
            }
        });

        txt33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt33FocusGained(evt);
            }
        });

        txt34.setEnabled(false);

        txt35.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt35FocusLost(evt);
            }
        });

        txt36.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt36FocusLost(evt);
            }
        });

        txt37.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt37FocusGained(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel38.setText("Đơn vị tiền : Việt Nam Đồng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(114, 114, 114)
                                .addComponent(txt4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt6)
                                    .addComponent(txt5)
                                    .addComponent(txt7))))
                        .addGap(815, 815, 815))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(701, 701, 701)
                                .addComponent(jLabel38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel15)
                                .addGap(176, 176, 176)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel20)
                                .addGap(192, 192, 192)
                                .addComponent(txt26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel30)
                                .addGap(189, 189, 189)
                                .addComponent(txt35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(613, 613, 613)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave)
                                .addGap(26, 26, 26)
                                .addComponent(btnClose))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(134, 134, 134)
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addGap(84, 84, 84)
                                        .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel36)
                                        .addGap(28, 28, 28)
                                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel14)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel10)
                                        .addGap(187, 187, 187)
                                        .addComponent(jLabel12)
                                        .addGap(353, 353, 353)
                                        .addComponent(jLabel11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(145, 145, 145)
                                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(161, 161, 161)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(193, 193, 193)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt22)
                                    .addComponent(txt23, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(191, 191, 191)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt27)
                                    .addComponent(txt28)
                                    .addComponent(txt29)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(185, 185, 185)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt25)
                                    .addComponent(txt24)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addGap(189, 189, 189)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt30)
                                    .addComponent(txt31)
                                    .addComponent(txt32)
                                    .addComponent(txt33)
                                    .addComponent(txt34)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(194, 194, 194)
                                        .addComponent(txt37))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addGap(188, 188, 188)
                                        .addComponent(txt36, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel38)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel19))
                    .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel20))
                    .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel24))
                    .addComponent(txt30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel25))
                    .addComponent(txt31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txt32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27))
                    .addComponent(txt33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel28))
                    .addComponent(txt34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30))
                    .addComponent(txt35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel31))
                    .addComponent(txt36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        new MainScreen(userAccountId, taxcode, name).setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        TaxDeclare dec = new TaxDeclare();
        if (jCheckBox1.isSelected()) {
            int userID = this.userAccountId;
            String taxPeriod = txt1.getText();
            String firstTime = txt2.getText();
            String timeUpdate = txt3.getText();
            float total = Float.parseFloat(txt34.getText());
            Timestamp createDate = new Timestamp(System.currentTimeMillis());
            User user = new User(userID);
            dec.setUser(user);
            dec.setTaxPeriod(taxPeriod);
            if (firstTime.equals("[X]")) {
                dec.setFirstTime(true);
            } else {
                dec.setFirstTime(false);
            }
            dec.setTime_update(timeUpdate);
            dec.setTotal(total);
            dec.setCreateDate(createDate);
            deDao.insertTaxDeclare(dec);
            JOptionPane.showMessageDialog(this, "Lưu khai báo thành công!");
        } else {
            int userID = this.userAccountId;
            String taxPeriod = txt1.getText();
            String firstTime = txt2.getText();
            String timeUpdate = txt3.getText();
            float total = Float.parseFloat(txt37.getText());
            Timestamp createDate = new Timestamp(System.currentTimeMillis());
            User user = new User(userID);
            dec.setUser(user);
            dec.setTaxPeriod(taxPeriod);
            if (firstTime.equals("[X]")) {
                dec.setFirstTime(true);
            } else {
                dec.setFirstTime(false);
            }
            dec.setTime_update(timeUpdate);
            dec.setTotal(total);
            dec.setCreateDate(createDate);
            deDao.insertTaxDeclare(dec);
            JOptionPane.showMessageDialog(this, "Lưu khai báo thành công!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        for (JTextField jt : listText) {
            jt.setText("");
        }
        if (jCheckBox1.isSelected()) {
            jCheckBox1.setSelected(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt22FocusLost
        try {
       if (!txt22.getText().equals("" )){
        if( Integer.parseInt(txt23.getText())<=0  ){
           setRedBorder(txt23);
           JOptionPane.showMessageDialog(this, "Vui lòng  nhập vào một số dương");
        }else {
          txt23.setBorder( new LineBorder(Color.black));
           updateTxT30();
           //updateTxt33();
         }
       }
       else {
           setRedBorder(txt23);
           JOptionPane.showMessageDialog(this, "Không để trống chỉ tiêu 22!");
       }
     }catch ( Exception e){
         e.toString();
     }
        
    }//GEN-LAST:event_txt22FocusLost

    private void txt23FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt23FocusLost
     try {
       if (!txt23.getText().equals("" )){
       if( Integer.parseInt(txt23.getText())<=0  ){
           setRedBorder(txt23);
           JOptionPane.showMessageDialog(this, "Vui lòng  nhập vào một số dương");
       }else if (Integer.parseInt(txt23.getText()) > Integer.parseInt(txt22.getText())) {
           setRedBorder(txt23);
           JOptionPane.showMessageDialog(this, "Nhập chỉ tiêu 23 nhỏ hơn hoặc bằng 22");
           checkRedBorder(txt23);
       }else {
          txt23.setBorder( new LineBorder(Color.black));
           updateTxT30();
           
         }
       }
       else {
           setRedBorder(txt23);
           JOptionPane.showMessageDialog(this, "Không để trống chỉ tiêu 23!");
       }
     }catch ( Exception e){
         e.toString();
     }
       
    }//GEN-LAST:event_txt23FocusLost

    private void txt27FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt27FocusLost
        try {
           txt27.setBorder( new LineBorder(Color.black));
            updateTxT24(txt27);
            updateTxT30 ();
        } catch (Exception  e ){
            e.toString();
        }
        
    }//GEN-LAST:event_txt27FocusLost

    private void txt28FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt28FocusLost
         try {
            txt28.setBorder( new LineBorder(Color.black));
            updateTxT24(txt28);
            updateTxT30 ();
         }catch (Exception e ){
             e.toString();
         }
        
    }//GEN-LAST:event_txt28FocusLost

    private void txt29FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt29FocusLost
       try {
        if (!txt29.getText().equals(""))
        if (Integer.parseInt(txt29.getText()) <0)
            setRedBorder(txt29);
        else {
           txt29.setBorder( new LineBorder(Color.black));
            updateTxT24(txt29);
            updateTxT30();
        }else {
            setRedBorder(txt23);
           JOptionPane.showMessageDialog(this, "Không để trống chỉ tiêu 29!");
        }
       } catch (Exception e){
           e.toString();
       }
    }//GEN-LAST:event_txt29FocusLost

    private void txt25FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt25FocusLost
     try {
      if (!txt25.getText().equals("")){
        if (Integer.parseInt(txt25.getText())% 9000000 != 0 ){
            
            setRedBorder(txt25);
            JOptionPane.showMessageDialog(this, "Nhập một số là bội của 9.000.000 VND");
        }else if(Integer.parseInt(txt25.getText()) > 27000000){
            setRedBorder(txt25);
            JOptionPane.showMessageDialog(this, "Số tiền không được vượt quá 27.000.000 VND");
        }else{
            txt25.setBorder( new LineBorder(Color.black));
            updateTxT24(txt25);
            updateTxT30 ();
        }
    }else {
          setRedBorder(txt25);
           JOptionPane.showMessageDialog(this, "Không bỏ trống chỉ tiêu 25");
      }
     } catch (Exception e ){
         e.toString();
     }
            
           
    }//GEN-LAST:event_txt25FocusLost

    private void txt26FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt26FocusLost
       try {
        if (!txt26.getText().equals("")){ 
        if (Integer.parseInt(txt26.getText())% 3600000 != 0   ){
             setRedBorder(txt26);
            JOptionPane.showMessageDialog(this, "Số tiền giảm trừ cho nguời phụ thuộc là 3.600.000/ 1 người/ 1 tháng");
         }else {
            txt26.setBorder( new LineBorder(Color.black));
             updateTxT24(txt26);
             updateTxT30 ();
         }
        }else {
             setRedBorder(txt26);
             JOptionPane.showMessageDialog(this, "Không bỏ trống chỉ tiêu 26");
        }
       } catch (Exception e ){
           e.toString();
       }
    }//GEN-LAST:event_txt26FocusLost

    private void txt24FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt24FocusGained
        
    }//GEN-LAST:event_txt24FocusGained

    private void txt32FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt32FocusLost
       try {
           int value32 = 0;
           if (!txt32.getText().equals("")){
               value32 = Integer.parseInt(txt32.getText());
               if (value32 > Integer.parseInt(txt32.getText()))
                   JOptionPane.showMessageDialog(this, "Tổng thu nhập chịu thuế làm căn cứ tính giảm thuế phải nhỏ hơn hoặc bằng Tổng thu nhập chịu thuế phát sinh trong kỳ (chỉ tiêu [22])");
                
           }
           
              
       } catch (Exception e){
           e.toString();
       }
    }//GEN-LAST:event_txt32FocusLost

    private void txt31FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt31FocusLost
       try {
          
          
       } catch (Exception e){
           e.toString();
       }
    }//GEN-LAST:event_txt31FocusLost

    private void txt35FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt35FocusLost
       try {
        if (txt35.getText().equals(""))
            txt35.setText(String.valueOf(0));
       } catch (Exception e ){
           e.toString();
       }
    }//GEN-LAST:event_txt35FocusLost

    private void txt36FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt36FocusLost
       try {
        if (txt36.getText().equals(""))
            txt36.setText(String.valueOf(0));
       } catch (Exception e ){
           e.toString();
       }
    }//GEN-LAST:event_txt36FocusLost

    private void txt31FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt31FocusGained
        updateTxT31();
    }//GEN-LAST:event_txt31FocusGained

    private void txt33FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt33FocusGained
        updateTxt33();
    }//GEN-LAST:event_txt33FocusGained

    private void txt37FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt37FocusGained
        updateTxt37();
    }//GEN-LAST:event_txt37FocusGained
       
       public void setRedBorder (JTextField textField){     
           textField.setBorder( new LineBorder(Color.RED, 2));
           
       }
       public int checkRedBorder (JTextField textField){
           LineBorder border = (LineBorder)textField.getBorder();
           return border.getLineColor().getRed();
       }
       
       public void updateTxT24 (JTextField txField){
           try{
           if (txt24.getText().equals(""))
               txt24.setText(String.valueOf(0 + Integer.parseInt(txField.getText())));
           else if (txField.getText().equals(""))
            txt24.setText(String.valueOf(Integer.parseInt(txt24.getText()) + 0));
           else
               txt24.setText(String.valueOf(Integer.parseInt(txt24.getText()) + Integer.parseInt(txField.getText())));
           
       
       } catch (Exception e ){
           e.toString();
    }
}
       
       public void updateTxT30 (){
           try {
            
           int value22 = 0;
           int value23 = 0;
           int value24 = 0;
           int value30 = 0;
           
           if (!txt22.getText().equals("")){
               value22 = Integer.parseInt(txt22.getText());
           }
           if (!txt23.getText().equals("")){
               value23 = Integer.parseInt(txt23.getText());
           }
           if (!txt24.getText().equals("")){
               value24 = Integer.parseInt(txt24.getText());
               
           }
            value30 = value22 - value23 - value24;
            if (value30 <= 0)
               txt30.setText(String.valueOf(0));
            else
                txt30.setText(String.valueOf(value30));
           
           
       }catch (Exception e ){
           e.toString();
       }
       }
       
       public void updateTxT31 (){
           try{
               
                int value30 = 0;
               
                if (txt30.getText().equals(""))
                    txt31.setText(String.valueOf(0));
                else {
                    value30 = Integer.parseInt(txt30.getText());
                    if (value30 <= 5000000){
                        int  fivePercen = (int) (Integer.parseInt(txt30.getText())/3 *0.05/100);   
                        txt31.setText(String.valueOf(fivePercen));         
                    }else if (value30 < 5000000 && value30 <= 10000000){
                       int  tenPercen = (int) (Integer.parseInt(txt30.getText())/3 *0.1/100); 
                        txt31.setText(String.valueOf(tenPercen));
                        
                    } else if (value30 > 10000000 && value30 <=18000000){
                         int  fifteenPercen = (int) (Integer.parseInt(txt30.getText())/3 *0.15/100);
                         txt31.setText(String.valueOf(fifteenPercen));
                    } else if (value30 > 18000000 && value30 <=32000000){
                         int  twentyPercen = (int) (Integer.parseInt(txt30.getText())/3 *0.2/100);
                         txt31.setText(String.valueOf(twentyPercen));
                    }else if (value30 > 32000000 && value30 <= 52000000){
                          int  twentyFivePercen = (int) (Integer.parseInt(txt30.getText())/3 *0.25/100);
                         txt31.setText(String.valueOf(twentyFivePercen));
                    }else if (value30 > 52000000 && value30 <= 80000000){
                          int  thirtyPercen = (int) (Integer.parseInt(txt30.getText())/3 *0.30/100);
                         txt31.setText(String.valueOf(thirtyPercen));
                    }else if (value30 > 80000000){
                           int  thirtyFivePercen = (int) (Integer.parseInt(txt30.getText())/3 *0.35/100);
                         txt31.setText(String.valueOf(thirtyFivePercen));
                    }
                    

                }
           }catch (Exception e){
               
           }          
       }
       
       public void updateTxt33 (){
           try {
               
              int value31 = 0;
              int value32 = 0;
              int value22 = 0;
              int value23 = 0;
           
            if (!txt31.getText().equals(""))
               value31 = Integer.parseInt(txt31.getText());       
            if (!txt32.getText().equals(""))
               value32 = Integer.parseInt(txt32.getText());
            if (!txt22.getText().equals(""))
               value22 = Integer.parseInt(txt22.getText());
            if (!txt23.getText().equals(""))
               value23 = Integer.parseInt(txt23.getText());
            
               System.out.println(value22 +" "+ value23 +" "+ value31+ " " + value32);
           
                int value33 =  (int) (value31 * (value32 / (value22 - value23))* 0.5);
                
               System.out.println(value33);
               
           
          txt33.setText(String.valueOf(value33));
          updateTxt34();
           } catch (Exception e){
               e.toString();
           }
              
        
}
       public void updateTxt34 (){
           try {
            int value31 = 0;
            int value33 = 0;
            
            
            if (!txt31.getText().equals(""))
               value31 = Integer.parseInt(txt31.getText());
            if (!txt32.getText().equals(""))
               value33 = Integer.parseInt(txt33.getText());
            
           int value34=  value31 - value33;
            
            txt34.setText(String.valueOf(value34));
             
           } catch (Exception e ){
               e.toString();
           }
       }
       
       public void updateTxt37 (){
           try {
           int value35 = 0;
           int value36 = 0;
           
           if (!txt35.getText().equals(""))
               value35 = Integer.parseInt(txt35.getText());
            if (!txt36.getText().equals(""))
               value36 = Integer.parseInt(txt36.getText());
            
            int value37 = value35 * value36 /100;
            
            txt37.setText(String.valueOf(value37));
           
           } catch (Exception e ){
               e.toString();
           }
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxDeclareView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxDeclareView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxDeclareView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxDeclareView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jf = new TaxDeclareView();

                jf.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt28;
    private javax.swing.JTextField txt29;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt30;
    private javax.swing.JTextField txt31;
    private javax.swing.JTextField txt32;
    private javax.swing.JTextField txt33;
    private javax.swing.JTextField txt34;
    private javax.swing.JTextField txt35;
    private javax.swing.JTextField txt36;
    private javax.swing.JTextField txt37;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
