/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author BVCN 88
 */
public class TaxPeriod extends javax.swing.JFrame {
        int userAccountId ;
        int taxcode;
        String name;
    public TaxPeriod( int userAccountID,int taxcode,String name) {
        initComponents();
        this.userAccountId  = userAccountID;
        this.taxcode= taxcode;
        this.name = name;
        time.setVisible(false);
        txtTime.setVisible(false);
        System.out.println(userAccountID);
        txtYear.setText(String.valueOf(Calendar.getInstance().get(Calendar.YEAR)));
    }

    public TaxPeriod() throws HeadlessException {
        initComponents();
        txtYear.setText(String.valueOf(Calendar.getInstance().get(Calendar.YEAR)));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taxPeriodCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        startMonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endMonth = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        time = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        btnAccess = new javax.swing.JButton();
        Closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chọn kỳ tính thuế");
        setName("Chọn kỳ tính thuế"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Quý");

        taxPeriodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4" }));
        taxPeriodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxPeriodComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Năm");

        jLabel3.setText("Từ tháng");

        jLabel4.setText("Đến tháng");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Tờ khai lần đầu");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tờ khai bổ sung");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        time.setText("Lần thứ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(time))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtYear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(endMonth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxPeriodCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 69, Short.MAX_VALUE)
                    .addComponent(txtTime))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(taxPeriodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(startMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(endMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(time)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnAccess.setText("Đồng ý");
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });

        Closebtn.setText("Đóng");
        Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnAccess)
                .addGap(18, 18, 18)
                .addComponent(Closebtn)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccess)
                    .addComponent(Closebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed
       
        if(!startMonth.getText().equals("") && !endMonth.getText().equals("")){
            int month = Calendar.getInstance().get(Calendar.MONTH)+1;
            System.out.println(month);
            if (taxPeriodCombo.getSelectedIndex()==0 &&  month <=3){
                 JOptionPane.showMessageDialog(this, "Hiện tại chưa hết thời gian của Quý 1, vui lòng chọn lại kì khai báo!");
            }else if (taxPeriodCombo.getSelectedIndex()==1 && month <=6){
                 JOptionPane.showMessageDialog(this, "Hiện tại chưa hết thời gian của Quý 2, vui lòng chọn lại kì khai báo!");
            }else if (taxPeriodCombo.getSelectedIndex()==2 && month <=9){
                 JOptionPane.showMessageDialog(this, "Hiện tại chưa hết thời gian của Quý 3, vui lòng chọn lại kì khai báo!");
            } else if (taxPeriodCombo.getSelectedIndex()==3 && month <=12){
                 JOptionPane.showMessageDialog(this, "Hiện tại chưa hết thời gian của Quý 4, vui lòng chọn lại kì khai báo!");
            }else{
            
        String taxPeriod = "Quý"+taxPeriodCombo.getSelectedItem().toString()+" ( Từ tháng "+startMonth.getText()+" đến tháng "+endMonth.getText()+")";
        String start = null;
        String time = null;
        if (jRadioButton1.isSelected()){
            start = "[X]";
            time = null;
        }else{
            start = null;
            time= txtTime.getText();
        }
        new TaxDeclareView(userAccountId ,taxPeriod, start, time,name,taxcode).setVisible(true);
        this.dispose();
            
            
            }
        }else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn quý khai báo thuế!");
        }
    }//GEN-LAST:event_btnAccessActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        this.time.setVisible(true);
        this.txtTime.setVisible(true);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        this.time.setVisible(false);
        this.txtTime.setVisible(false);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebtnActionPerformed
         new MainScreen(userAccountId, taxcode, name).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClosebtnActionPerformed

    private void taxPeriodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxPeriodComboActionPerformed
    
            if(taxPeriodCombo.getSelectedIndex()==0){
                startMonth.setText("1/"+txtYear.getText());
                endMonth.setText("3/"+txtYear.getText());
                
            }else  if(taxPeriodCombo.getSelectedIndex()==1){
                startMonth.setText("4/"+txtYear.getText());
                endMonth.setText("6/"+txtYear.getText());
                
            } else  if(taxPeriodCombo.getSelectedIndex()==2){
                startMonth.setText("7/"+txtYear.getText());
                endMonth.setText("9/"+txtYear.getText());
                
            } else  if(taxPeriodCombo.getSelectedIndex()==3){
                startMonth.setText("10/"+txtYear.getText());
                endMonth.setText("12/"+txtYear.getText());
            }else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn kì nộp thuế!");
            }
        
    }//GEN-LAST:event_taxPeriodComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxPeriod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxPeriod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Closebtn;
    private javax.swing.JButton btnAccess;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField endMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField startMonth;
    private javax.swing.JComboBox<String> taxPeriodCombo;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
